# Generated by Django 5.2.6 on 2025-09-29 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thumbs_up', models.IntegerField(default=0)),
                ('heart', models.IntegerField(default=0)),
                ('laugh', models.IntegerField(default=0)),
                ('surprise', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'presentations',
                'ordering': ['-created_at'],
            },
        ),
    ]
