# Generated by Django 5.2.6 on 2025-09-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
